name: orocloud
description: "Cloud Based Storage Solution"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.9  # For SVG icons
  google_fonts: ^6.2.1  # Optional: If you want custom fonts
  

  # Authentication & Storage
  supabase_flutter: ^2.8.3
  shared_preferences: ^2.5.2

  # Document Scanning
  cunning_document_scanner: ^1.2.3
  flutter_launcher_icons: ^0.14.3
  file_picker: ^9.0.1
  path_provider: ^2.1.5
  pdf: ^3.11.3
  open_file: ^3.5.10
  flutter_pdfview: ^1.4.0
  dio: ^5.8.0+1
  share_plus: ^10.1.4
  url_launcher: ^6.3.1  

  image_picker: ^1.1.2
  image_cropper: ^9.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.14.3"
  flutter_native_splash: "^2.3.6"

flutter:
  uses-material-design: true

  # Asset Management (Add Google logo or other images)
  assets:
    - assets/google_logo.png  # Ensure the image exists in the assets folder

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/app_logo.png"
    background_color: "#42A2EE"
    theme_color: "#2484D0"
  windows:
    generate: true
    image_path: "assets/app_logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/app_logo.png"

flutter_native_splash:
  color: "#FFFFFF" # Use the background color of your icon
  image: assets/app_logo.png
  color_dark: "#000000" # Black for dark mode
  image_dark: assets/app_logo.png
  android_12:
    image: assets/app_logo.png
    icon_background_color: "#42A2EE"
    image_dark: assets/app_logo.png
    icon_background_color_dark: "#000000"
